name: membership-analysis-workflow
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - snakemake
  - pandas
  - matplotlib
  - seaborn
  - graphviz # for visualizing the workflow (DAG) 